export const FETCH_PICKUPLOCATION_REQUEST = "FETCH_PICKUPLOCATION_REQUEST";
export const FETCH_PICKUPLOCATION_SUCCESS = "FETCH_PICKUPLOCATION_SUCCESS";
export const FETCH_PICKUPLOCATION_FAILURE = "FETCH_PICKUPLOCATION_FAILURE";

export const ADD_PICKUPLOCATION_REQUEST = "ADD_PICKUPLOCATION_REQUEST";
export const ADD_PICKUPLOCATION_SUCCESS = "ADD_PICKUPLOCATION_SUCCESS";
export const ADD_PICKUPLOCATION_FAILURE = "ADD_PICKUPLOCATION_FAILURE";

export const DELETE_PICKUPLOCATION_REQUEST = "DELETE_PICKUPLOCATION_REQUEST";
export const DELETE_PICKUPLOCATION_SUCCESS = "DELETE_PICKUPLOCATION_SUCCESS";
export const DELETE_PICKUPLOCATION_FAILURE = "DELETE_PICKUPLOCATION_FAILURE";

export const UPDATE_PICKUPLOCATION_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_PICKUPLOCATION_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_PICKUPLOCATION_FAILURE = "UPDATE_PICKUPLOCATION_FAILURE";