export const UPDATE_USERPROFILE_REQUEST = 'UPDATE_USERPROFILE_REQUEST';
export const UPDATE_USERPROFILE_SUCCESS = 'UPDATE_USERPROFILE_SUCCESS';
export const UPDATE_USERPROFILE_FAILURE = 'UPDATE_USERPROFILE_FAILURE';